---
title: "Ejemplos Para la Visualización web de Estadísticas e Indicadores"
---

## Tipos de Gráficos para Estadísticas

* [Diag de barras](https://estadisticaun.github.io/Graficos/Series/J1_G2_I1_PEAMA_F5.html)

* [Tortas (Pie)](https://estadisticaun.github.io/Graficos/Series/J1_G2_I1_ADMITIDOS_F4.html)

* [Series de tiempo](https://estadisticaun.github.io/Graficos/Series/J1_G2_I1_ADMITIDOS_F16.html)

* [Tablas](https://estadisticaun.github.io/Graficos/Series/J1_G2_I1_ADMITIDO_F17.html)

* [Mapas](https://estadisticaun.github.io/Graficos/Mapas/municipios1.html)

## Tipos de gráficos Para Indicadores de Gestión

## Calibradores (Gauges)

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(rAmCharts)
p <- amAngularGauge(x = 25)
p
```


## Calibradores (Gauges)

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(rAmCharts)
p <- amSolidGauge(x = 65, text = "%", type = "semi")
p
```

## Gráficos de tiro (Bullets)

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(rAmCharts)
p <- amBullet(value = 50, val_color = "gray")
p
```


